language: node_js
node_js:
  - "8"
script:
  - yarn lint
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    only:
      branch: gh-pages
